FROM node:20 AS builder
WORKDIR /app
COPY package*.json ./
COPY packages/shared/package*.json ./packages/shared/
COPY apps/api/package*.json ./apps/api/
COPY prisma ./prisma
RUN npm install
COPY . .
RUN npx prisma generate
RUN npm run build --workspace=packages/shared
RUN npm run build --workspace=apps/api

FROM node:20 AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/packages/shared ./packages/shared
COPY --from=builder /app/apps/api ./apps/api
COPY --from=builder /app/prisma ./prisma

EXPOSE 4000
CMD ["sh", "-c", "./node_modules/.bin/prisma db push --accept-data-loss && node apps/api/dist/server.js"]
