FROM node:20-alpine AS builder
RUN apk add --no-cache openssl libc6-compat
WORKDIR /app
COPY package*.json ./
COPY packages/shared/package*.json ./packages/shared/
COPY apps/worker/package*.json ./apps/worker/
COPY prisma ./prisma
RUN npm install
COPY . .
RUN npx prisma generate
RUN npm run build --workspace=packages/shared
RUN npm run build --workspace=apps/worker

FROM node:20-alpine AS runner
RUN apk add --no-cache openssl libc6-compat
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/packages/shared ./packages/shared
COPY --from=builder /app/apps/worker ./apps/worker
COPY --from=builder /app/prisma ./prisma

EXPOSE 4001
CMD ["sh", "-c", "node apps/worker/dist/index.js"]
